apiVersion: v2
name: op-kits
description: Operator Kits Helm Chart
type: application
version: 0.1.11-rc.2
home: https://helm.rasa.com/
sources:
  - https://helm.rasa.com/charts/op-kits
keywords:
  - postgresql
  - kafka
  - cloudnativepg
  - strimzi
  - operators
  - database
  - messaging
maintainers:
  - name: Rasa Infrastructure and Security Team
    url: https://github.com/RasaHQ/rasa-helm-charts
    email: support@rasa.com
