{{- if and .Values.actionServer.enabled .Values.actionServer.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "rasa.fullname" . }}-action-server
  labels:
    {{- include "rasa.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "rasa.fullname" . }}-action-server
  minReplicas: {{ .Values.actionServer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.actionServer.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.actionServer.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.actionServer.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.actionServer.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.actionServer.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
