apiVersion: v1
entries:
  op-kits:
  - apiVersion: v2
    created: "2025-10-27T10:22:53.637529925Z"
    description: Operator Kits Helm Chart
    digest: 91c4413dacd3dd0d892a090f186036455016a4dfd03ea98cd59e301417ed5778
    home: https://helm.rasa.com/
    keywords:
    - postgresql
    - kafka
    - cloudnativepg
    - strimzi
    - operators
    - database
    - messaging
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: op-kits
    sources:
    - https://helm.rasa.com/charts/op-kits
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/op-kits-0.1.8/op-kits-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    created: "2025-10-22T12:19:35.08589846Z"
    description: Operator Kits Helm Chart
    digest: 96ea9e78cce8e0810122969f6e873cbb52c2d9409a0780513504624d2a6b9432
    home: https://helm.rasa.com/
    keywords:
    - postgresql
    - kafka
    - cloudnativepg
    - strimzi
    - operators
    - database
    - messaging
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: op-kits
    sources:
    - https://helm.rasa.com/charts/op-kits
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/op-kits-0.1.7/op-kits-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    created: "2025-10-14T12:41:45.58061768Z"
    description: Operator Kits Helm Chart
    digest: 2ea5cf9bd8e3ea4da360994dc53c193157b27ebf93708ceb1e8c4ae20a5a28fd
    home: https://helm.rasa.com/
    keywords:
    - postgresql
    - kafka
    - cloudnativepg
    - strimzi
    - operators
    - database
    - messaging
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: op-kits
    sources:
    - https://helm.rasa.com/charts/op-kits
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/op-kits-0.1.6/op-kits-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    created: "2025-10-03T13:27:32.886451322Z"
    description: Operator Kits Helm Chart
    digest: 940429f357df2084eda7542072ba83ea5805d3b2e7e074b05f805c7f342556e5
    home: https://helm.rasa.com/
    keywords:
    - postgresql
    - kafka
    - cloudnativepg
    - strimzi
    - operators
    - database
    - messaging
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: op-kits
    sources:
    - https://helm.rasa.com/charts/op-kits
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/op-kits-0.1.5/op-kits-0.1.5.tgz
    version: 0.1.5
  rasa:
  - apiVersion: v2
    created: "2025-10-10T09:59:52.173422728Z"
    description: A Rasa Pro Helm chart for Kubernetes
    digest: 61bbb7ca1fa0586e3fe36cb2d464475ebe2c55cd5970256df0fa5b1706548b0b
    home: https://rasa.com
    keywords:
    - Kubernetes
    - Rasa
    - Rasa Pro
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: rasa
    sources:
    - https://github.com/RasaHQ/rasa-helm-charts/tree/main/charts/rasa
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/rasa-1.3.0/rasa-1.3.0.tgz
    version: 1.3.0
  - apiVersion: v2
    created: "2025-10-09T13:15:14.689519547Z"
    description: A Rasa Pro Helm chart for Kubernetes
    digest: 5079054ef842d6d4f0ef214c57821652684a3132b04c0525f801ef4ba51f08a6
    home: https://rasa.com
    keywords:
    - Kubernetes
    - Rasa
    - Rasa Pro
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: rasa
    sources:
    - https://github.com/RasaHQ/rasa-helm-charts/tree/main/charts/rasa
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/rasa-1.2.7/rasa-1.2.7.tgz
    version: 1.2.7
  studio:
  - apiVersion: v2
    created: "2025-10-29T11:56:52.661475208Z"
    dependencies:
    - condition: replicated.enabled
      name: replicated
      repository: oci://registry.replicated.com/library
      version: 1.8.1
    - condition: rasa.enabled
      name: rasa
      repository: oci://europe-west3-docker.pkg.dev/rasa-releases/helm-charts
      version: 1.3.0
    description: This chart bootstraps Studio deployment on a Kubernetes cluster using
      the Helm package manager.
    digest: 37814812af3ecfdc229ec99e6b5d1bed0a266480363598873a897fd7f7411f57
    home: https://helm.rasa.com
    keywords:
    - Kubernetes
    - Studio
    - CALM
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: studio
    sources:
    - https://github.com/RasaHQ/rasa-helm-charts/tree/main/charts/studio
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/studio-2.2.1/studio-2.2.1.tgz
    version: 2.2.1
  - apiVersion: v2
    created: "2025-10-21T12:52:13.212204638Z"
    dependencies:
    - condition: replicated.enabled
      name: replicated
      repository: oci://registry.replicated.com/library
      version: 1.8.1
    - condition: rasa.enabled
      name: rasa
      repository: oci://europe-west3-docker.pkg.dev/rasa-releases/helm-charts
      version: 1.3.0
    description: This chart bootstraps Studio deployment on a Kubernetes cluster using
      the Helm package manager.
    digest: 983f791722cd656b736eb1a4ef702df1ff18540a0552274efc2fa3108364fc69
    home: https://helm.rasa.com
    keywords:
    - Kubernetes
    - Studio
    - CALM
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: studio
    sources:
    - https://github.com/RasaHQ/rasa-helm-charts/tree/main/charts/studio
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/studio-2.2.0/studio-2.2.0.tgz
    version: 2.2.0
    deprecated: true
    annotations:
      note: "ðŸš¨ This chart version is yanked due to a critical bug. Please use 2.2.1 or newer."
  - apiVersion: v2
    created: "2025-10-09T13:17:48.554276319Z"
    dependencies:
    - condition: replicated.enabled
      name: replicated
      repository: oci://registry.replicated.com/library
      version: 1.7.1
    - condition: rasa.enabled
      name: rasa
      repository: oci://europe-west3-docker.pkg.dev/rasa-releases/helm-charts
      version: 1.2.7
    description: This chart bootstraps Studio deployment on a Kubernetes cluster using
      the Helm package manager.
    digest: 29eba68383b416ec6c1faee6048edf9d41fadbf001ddc91874c8944501bb568f
    home: https://helm.rasa.com
    keywords:
    - Kubernetes
    - Studio
    - CALM
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: studio
    sources:
    - https://github.com/RasaHQ/rasa-helm-charts/tree/main/charts/studio
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/studio-2.1.9/studio-2.1.9.tgz
    version: 2.1.9
generated: "2025-10-29T11:56:52.661499402Z"
