apiVersion: v1
entries:
  op-kits:
  - apiVersion: v2
    created: "2025-12-12T11:01:22.664798663Z"
    description: Operator Kits Helm Chart
    digest: 37269efb1760a79142caf891b42b7fd9e1022df4c58f825ac077bd80047d59dc
    home: https://helm.rasa.com/
    keywords:
    - postgresql
    - kafka
    - cloudnativepg
    - strimzi
    - operators
    - database
    - messaging
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: op-kits
    sources:
    - https://helm.rasa.com/charts/op-kits
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/op-kits-0.2.2/op-kits-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    created: "2025-11-28T11:06:21.695365746Z"
    description: Operator Kits Helm Chart
    digest: 51057d41ee1271c508f04b3a115d85b7787f0c2bbf9b7f364246a79062020392
    home: https://helm.rasa.com/
    keywords:
    - postgresql
    - kafka
    - cloudnativepg
    - strimzi
    - operators
    - database
    - messaging
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: op-kits
    sources:
    - https://helm.rasa.com/charts/op-kits
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/op-kits-0.2.1/op-kits-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    created: "2025-11-27T19:02:38.357956857Z"
    description: Operator Kits Helm Chart
    digest: 8c6052b54b5d3a89371784c704c542b97b56f878131ad22f4bace328f5aa0513
    home: https://helm.rasa.com/
    keywords:
    - postgresql
    - kafka
    - cloudnativepg
    - strimzi
    - operators
    - database
    - messaging
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: op-kits
    sources:
    - https://helm.rasa.com/charts/op-kits
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/op-kits-0.2.0/op-kits-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    created: "2025-11-25T11:57:32.910119766Z"
    description: Operator Kits Helm Chart
    digest: af50029db14b8535ede005fe938ffe905c68d42a7b7e1c8d49a65bf166366c1e
    home: https://helm.rasa.com/
    keywords:
    - postgresql
    - kafka
    - cloudnativepg
    - strimzi
    - operators
    - database
    - messaging
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: op-kits
    sources:
    - https://helm.rasa.com/charts/op-kits
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/op-kits-0.1.10/op-kits-0.1.10.tgz
    version: 0.1.10
  - apiVersion: v2
    created: "2025-11-18T12:53:04.251970414Z"
    description: Operator Kits Helm Chart
    digest: 3da6b62de707bfe97136428737535fb982c8f0b81e835f98890b94569926a67f
    home: https://helm.rasa.com/
    keywords:
    - postgresql
    - kafka
    - cloudnativepg
    - strimzi
    - operators
    - database
    - messaging
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: op-kits
    sources:
    - https://helm.rasa.com/charts/op-kits
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/op-kits-0.1.9/op-kits-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    created: "2025-10-27T10:22:53.637529925Z"
    description: Operator Kits Helm Chart
    digest: 91c4413dacd3dd0d892a090f186036455016a4dfd03ea98cd59e301417ed5778
    home: https://helm.rasa.com/
    keywords:
    - postgresql
    - kafka
    - cloudnativepg
    - strimzi
    - operators
    - database
    - messaging
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: op-kits
    sources:
    - https://helm.rasa.com/charts/op-kits
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/op-kits-0.1.8/op-kits-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    created: "2025-10-22T12:19:35.08589846Z"
    description: Operator Kits Helm Chart
    digest: 96ea9e78cce8e0810122969f6e873cbb52c2d9409a0780513504624d2a6b9432
    home: https://helm.rasa.com/
    keywords:
    - postgresql
    - kafka
    - cloudnativepg
    - strimzi
    - operators
    - database
    - messaging
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: op-kits
    sources:
    - https://helm.rasa.com/charts/op-kits
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/op-kits-0.1.7/op-kits-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    created: "2025-10-14T12:41:45.58061768Z"
    description: Operator Kits Helm Chart
    digest: 2ea5cf9bd8e3ea4da360994dc53c193157b27ebf93708ceb1e8c4ae20a5a28fd
    home: https://helm.rasa.com/
    keywords:
    - postgresql
    - kafka
    - cloudnativepg
    - strimzi
    - operators
    - database
    - messaging
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: op-kits
    sources:
    - https://helm.rasa.com/charts/op-kits
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/op-kits-0.1.6/op-kits-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    created: "2025-10-03T13:27:32.886451322Z"
    description: Operator Kits Helm Chart
    digest: 940429f357df2084eda7542072ba83ea5805d3b2e7e074b05f805c7f342556e5
    home: https://helm.rasa.com/
    keywords:
    - postgresql
    - kafka
    - cloudnativepg
    - strimzi
    - operators
    - database
    - messaging
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: op-kits
    sources:
    - https://helm.rasa.com/charts/op-kits
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/op-kits-0.1.5/op-kits-0.1.5.tgz
    version: 0.1.5
  rasa:
  - apiVersion: v2
    created: "2025-12-12T11:01:22.922323092Z"
    description: A Rasa Pro Helm chart for Kubernetes
    digest: 9ac14a9ca0144a59659bd6a5431d9a192c3ddfac53bc6e7c22f3fedf7b8b8ec7
    home: https://rasa.com
    keywords:
    - Kubernetes
    - Rasa
    - Rasa Pro
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: rasa
    sources:
    - https://github.com/RasaHQ/rasa-helm-charts/tree/main/charts/rasa
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/rasa-2.0.1/rasa-2.0.1.tgz
    version: 2.0.1
  - apiVersion: v2
    created: "2025-11-25T11:57:33.169193269Z"
    description: A Rasa Pro Helm chart for Kubernetes
    digest: a6466c29a9665bebd5da2c0c002e913e32c845c4c3b11de25fe3d9fbbc890ec2
    home: https://rasa.com
    keywords:
    - Kubernetes
    - Rasa
    - Rasa Pro
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: rasa
    sources:
    - https://github.com/RasaHQ/rasa-helm-charts/tree/main/charts/rasa
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/rasa-2.0.0/rasa-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v2
    created: "2025-11-14T10:46:22.474275229Z"
    description: A Rasa Pro Helm chart for Kubernetes
    digest: b4b86035e95af5b8742bfd3eb9bd7e6883b770a46c103a5b567229d3f8aceecd
    home: https://rasa.com
    keywords:
    - Kubernetes
    - Rasa
    - Rasa Pro
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: rasa
    sources:
    - https://github.com/RasaHQ/rasa-helm-charts/tree/main/charts/rasa
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/rasa-1.3.2/rasa-1.3.2.tgz
    version: 1.3.2
  - apiVersion: v2
    created: "2025-11-13T22:11:05.252272002Z"
    description: A Rasa Pro Helm chart for Kubernetes
    digest: 530d5ecc71e4bed3c81d66faf0e16b302a16d66744c478886532236b68a3e5db
    home: https://rasa.com
    keywords:
    - Kubernetes
    - Rasa
    - Rasa Pro
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: rasa
    sources:
    - https://github.com/RasaHQ/rasa-helm-charts/tree/main/charts/rasa
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/rasa-1.3.1/rasa-1.3.1.tgz
    version: 1.3.1
  - apiVersion: v2
    created: "2025-10-10T09:59:52.173422728Z"
    description: A Rasa Pro Helm chart for Kubernetes
    digest: 61bbb7ca1fa0586e3fe36cb2d464475ebe2c55cd5970256df0fa5b1706548b0b
    home: https://rasa.com
    keywords:
    - Kubernetes
    - Rasa
    - Rasa Pro
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: rasa
    sources:
    - https://github.com/RasaHQ/rasa-helm-charts/tree/main/charts/rasa
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/rasa-1.3.0/rasa-1.3.0.tgz
    version: 1.3.0
  - apiVersion: v2
    created: "2025-10-09T13:15:14.689519547Z"
    description: A Rasa Pro Helm chart for Kubernetes
    digest: 5079054ef842d6d4f0ef214c57821652684a3132b04c0525f801ef4ba51f08a6
    home: https://rasa.com
    keywords:
    - Kubernetes
    - Rasa
    - Rasa Pro
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: rasa
    sources:
    - https://github.com/RasaHQ/rasa-helm-charts/tree/main/charts/rasa
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/rasa-1.2.7/rasa-1.2.7.tgz
    version: 1.2.7
  studio:
  - apiVersion: v2
    created: "2025-12-12T11:01:23.188766887Z"
    dependencies:
    - condition: replicated.enabled
      name: replicated
      repository: oci://registry.replicated.com/library
      version: 1.8.1
    - condition: rasa.enabled
      name: rasa
      repository: oci://europe-west3-docker.pkg.dev/rasa-releases/helm-charts
      version: 2.0.0
    description: A Rasa Studio Helm chart for Kubernetes
    digest: 2a12ebda439dfa7035dfa6e6071b85d5fbb8e4ebbedc27c5a3cfdbf6d0592e7c
    home: https://helm.rasa.com
    keywords:
    - Kubernetes
    - Studio
    - CALM
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: studio
    sources:
    - https://github.com/RasaHQ/rasa-helm-charts/tree/main/charts/studio
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/studio-2.2.4/studio-2.2.4.tgz
    version: 2.2.4
  - apiVersion: v2
    created: "2025-12-11T13:44:00.085668571Z"
    dependencies:
    - condition: replicated.enabled
      name: replicated
      repository: oci://registry.replicated.com/library
      version: 1.8.1
    - condition: rasa.enabled
      name: rasa
      repository: oci://europe-west3-docker.pkg.dev/rasa-releases/helm-charts
      version: 2.0.0
    description: A Rasa Studio Helm chart for Kubernetes
    digest: 749e1029cd9495185f8ed1d186cd5cb8b0d79f32185ab59172ace2b8a742a638
    home: https://helm.rasa.com
    keywords:
    - Kubernetes
    - Studio
    - CALM
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: studio
    sources:
    - https://github.com/RasaHQ/rasa-helm-charts/tree/main/charts/studio
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/studio-2.2.3/studio-2.2.3.tgz
    version: 2.2.3
  - apiVersion: v2
    created: "2025-11-17T09:46:39.216429388Z"
    dependencies:
    - condition: replicated.enabled
      name: replicated
      repository: oci://registry.replicated.com/library
      version: 1.8.1
    - condition: rasa.enabled
      name: rasa
      repository: oci://europe-west3-docker.pkg.dev/rasa-releases/helm-charts
      version: 1.3.2
    description: This chart bootstraps Studio deployment on a Kubernetes cluster using
      the Helm package manager.
    digest: cae018dc6cccca309a9570d28d744b293de45b919bce18dfb3be7d5f8ed74714
    home: https://helm.rasa.com
    keywords:
    - Kubernetes
    - Studio
    - CALM
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: studio
    sources:
    - https://github.com/RasaHQ/rasa-helm-charts/tree/main/charts/studio
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/studio-2.2.2/studio-2.2.2.tgz
    version: 2.2.2
  - apiVersion: v2
    created: "2025-10-29T11:56:52.661475208Z"
    dependencies:
    - condition: replicated.enabled
      name: replicated
      repository: oci://registry.replicated.com/library
      version: 1.8.1
    - condition: rasa.enabled
      name: rasa
      repository: oci://europe-west3-docker.pkg.dev/rasa-releases/helm-charts
      version: 1.3.0
    description: This chart bootstraps Studio deployment on a Kubernetes cluster using
      the Helm package manager.
    digest: 37814812af3ecfdc229ec99e6b5d1bed0a266480363598873a897fd7f7411f57
    home: https://helm.rasa.com
    keywords:
    - Kubernetes
    - Studio
    - CALM
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: studio
    sources:
    - https://github.com/RasaHQ/rasa-helm-charts/tree/main/charts/studio
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/studio-2.2.1/studio-2.2.1.tgz
    version: 2.2.1
  - apiVersion: v2
    created: "2025-10-21T12:52:13.212204638Z"
    dependencies:
    - condition: replicated.enabled
      name: replicated
      repository: oci://registry.replicated.com/library
      version: 1.8.1
    - condition: rasa.enabled
      name: rasa
      repository: oci://europe-west3-docker.pkg.dev/rasa-releases/helm-charts
      version: 1.3.0
    description: This chart bootstraps Studio deployment on a Kubernetes cluster using
      the Helm package manager.
    digest: 983f791722cd656b736eb1a4ef702df1ff18540a0552274efc2fa3108364fc69
    home: https://helm.rasa.com
    keywords:
    - Kubernetes
    - Studio
    - CALM
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: studio
    sources:
    - https://github.com/RasaHQ/rasa-helm-charts/tree/main/charts/studio
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/studio-2.2.0/studio-2.2.0.tgz
    version: 2.2.0
  - apiVersion: v2
    created: "2025-10-09T13:17:48.554276319Z"
    dependencies:
    - condition: replicated.enabled
      name: replicated
      repository: oci://registry.replicated.com/library
      version: 1.7.1
    - condition: rasa.enabled
      name: rasa
      repository: oci://europe-west3-docker.pkg.dev/rasa-releases/helm-charts
      version: 1.2.7
    description: This chart bootstraps Studio deployment on a Kubernetes cluster using
      the Helm package manager.
    digest: 29eba68383b416ec6c1faee6048edf9d41fadbf001ddc91874c8944501bb568f
    home: https://helm.rasa.com
    keywords:
    - Kubernetes
    - Studio
    - CALM
    maintainers:
    - email: support@rasa.com
      name: Rasa Infrastructure and Security Team
      url: https://github.com/RasaHQ/rasa-helm-charts
    name: studio
    sources:
    - https://github.com/RasaHQ/rasa-helm-charts/tree/main/charts/studio
    type: application
    urls:
    - https://github.com/RasaHQ/rasa-helm-charts/releases/download/studio-2.1.9/studio-2.1.9.tgz
    version: 2.1.9
generated: "2025-12-12T11:01:23.188837569Z"
