apiVersion: v2
name: studio
description: A Rasa Studio Helm chart for Kubernetes
type: application
version: 2.2.5-rc.2
home: https://helm.rasa.com
sources:
  - https://github.com/RasaHQ/rasa-helm-charts/tree/main/charts/studio
keywords:
  - Kubernetes
  - Studio
  - CALM
maintainers:
  - name: Rasa Infrastructure and Security Team
    url: https://github.com/RasaHQ/rasa-helm-charts
    email: support@rasa.com
dependencies:
  - name: replicated
    condition: replicated.enabled
    repository: oci://registry.replicated.com/library
    version: 1.8.1
  - name: rasa
    condition: rasa.enabled
    repository: oci://europe-west3-docker.pkg.dev/rasa-releases/helm-charts
    version: 2.0.0
