{{- if .Values.eventIngestion.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "studio.fullname" . }}-event-ingestion-hpa
  labels:
    {{- include "studio.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "studio.fullname" . }}-event-ingestion
  minReplicas: {{ .Values.eventIngestion.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.eventIngestion.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.eventIngestion.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.eventIngestion.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.eventIngestion.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.eventIngestion.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
