{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rasa-pro.serviceAccountName" . }}
  labels:
    {{- include "rasa-pro.labels" . | nindent 4 }}
  {{- with .Values.rasaPro.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
