apiVersion: v2
name: rasa
description: A Rasa Pro Helm chart for Kubernetes
type: application
version: 1.3.2
home: https://rasa.com
sources:
  - https://github.com/RasaHQ/rasa-helm-charts/tree/main/charts/rasa
keywords:
  - Kubernetes
  - Rasa
  - Rasa Pro
maintainers:
  - name: Rasa Infrastructure and Security Team
    url: https://github.com/RasaHQ/rasa-helm-charts
    email: support@rasa.com
