---
name: Release Op-Kits Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/op-kits/**'
      - '!charts/rasa/**'
      - '!charts/studio/**'
      - '!replicated/**'

env:
  ARTIFACT_REGISTRY: europe-west3-docker.pkg.dev
  HELM_REPOSITORY: rasa-releases
  HELM_CHART: helm-charts

jobs:
  release:
    runs-on: ubuntu-24.04
    outputs:
      op-kits-version: ${{ steps.chart-info.outputs.version }}

    permissions:
      contents: write
      id-token: write
      pull-requests: read
      issues: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Install Helm 3
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78
        with:
          version: v3.15.2

      - name: Authenticate to Google Cloud
        id: google-auth
        uses: google-github-actions/auth@71fee32a0bb7e97b4d33d548e7d957010649d8fa
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_OIDC_HELM }}
          service_account: '${{ secrets.SERVICE_ACCOUNT_OIDC_HELM }}'

      - name: Read Helm Chart
        id: chart-info
        uses: miraai/read-helm-chart-yaml@9a798908719da8d062b86097d4ff1ad85abfc7aa
        with:
          path: charts/op-kits/

      - name: Package and push chart
        id: release
        env:
          ACCESS_TOKEN: ${{ steps.google-auth.outputs.access_token }}
          CHART_PATH: charts/op-kits
          CHART_URI: oci://${{ env.ARTIFACT_REGISTRY }}/${{ env.HELM_REPOSITORY }}/${{ env.HELM_CHART }}
          CHART_TAR: ${{ steps.chart-info.outputs.name }}-${{ steps.chart-info.outputs.version }}.tgz
          REGISTRY_URL: https://${{ env.ARTIFACT_REGISTRY }}
        run: |
          echo "${ACCESS_TOKEN}" | helm registry login -u oauth2accesstoken --password-stdin "${REGISTRY_URL}"
          helm dependency update "${CHART_PATH}"
          helm package "${CHART_PATH}"
          helm push "${CHART_TAR}" "${CHART_URI}"
          echo "uri=${CHART_URI}" >> $GITHUB_OUTPUT

      - name: Notify Slack of successful release ğŸ’¬
        if: steps.release.outcome == 'success'
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844
        with:
          # Send notication to #release slack channel
          channel-id: 'C0351QXJ5CP'
          slack-message: "ğŸš€ New *Op-Kits* Helm Chart version `${{ steps.chart-info.outputs.name }}-${{ steps.chart-info.outputs.version }}` has been released!"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Notify Slack of unsuccessful release â›”ï¸
        if: steps.release.outcome == 'failure'
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844
        with:
          # Send notication to #release slack channel
          channel-id: 'C0351QXJ5CP'
          slack-message: "â›”ï¸ *Op-Kits* Helm Chart version `${{ steps.chart-info.outputs.name }}-${{ steps.chart-info.outputs.version }}` could not be released ğŸ˜±! Please check out <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Github Action workflow log>"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
